### PR TITLE
Separate calling handler and executing session action

### LINKED ISSUE #21: Separate calling handler and executing session action
Session action would not be executed if handler is nil.

https://github.com/authgear/authgear-sdk-ios/blob/1881bab369a8280401514100725de0f7e35b5af2/Sources/Authgear.swift#L520

### PR DESCRIPTION
**Pull request by nicolaslee2775**
based on PR #20
fix #21

### CODE REVIEW

**Comment by louischan-oursky** [comment]
conflicted.

**Comment by nicolaslee2775** [comment]
@louischan-oursky Rebased.

**Comment by louischan-oursky** [comment]
Please rebase.

**Comment by nicolaslee2775** [comment]
@louischan-oursky Rebased.

**Pull request merged**
