### PR TITLE
Add common ui parameters to ios sdk

### PR DESCRIPTION
**Pull request by tung2744**

### CODE REVIEW

**Comment by louischan-oursky** [comment]
I have fixed the lint error on branch `2023C01`, you may rebase.

**Review by louischan-oursky — COMMENTED** [review]
1. Remove customUIQuery from authenticate()
2. Change ResetLinkHandler to take URL instead of URLQueryItem. And then use URL.query to forward the query (of type String) directly.

**Comment by tung2744** [comment]
@louischan-oursky `customUIQuery` also exist in Authgear api, should I remove it from latte only?

**Comment by louischan-oursky** [comment]
Please also remove it from Authgear API.

**Comment by tung2744** [comment]
@louischan-oursky Updated, thanks!

**Pull request merged**
