### PR TITLE
Fixed access token expiry check not having threshold

### LINKED ISSUE #7: Fix session expiry checking not having a reasonable threshold

### PR DESCRIPTION
**Pull request by nicolaslee2775**
fix #7

### CODE REVIEW

**Comment by nicolaslee2775** [comment]
`swiftformat` is upgraded to 0.47.2.

**Review by axolotl0212 — APPROVED** [review]

**Comment by nicolaslee2775** [comment]
@axolotl0212 @louischan-oursky Fixed.

**Comment by axolotl0212** [comment]
For commit 968ab6f, have you tried only disable the corresponding line + rule using inline comment? 
ref: https://github.com/nicklockwood/SwiftFormat#rules

**Comment by nicolaslee2775** [comment]
@axolotl0212 Updated. Used inline comment to disable swiftformat for specific lines.

**Comment by nicolaslee2775** [comment]
@louischan-oursky @axolotl0212 The lint error was handled via PR #28.

**Comment by louischan-oursky** [comment]
Please rebase.

**Comment by nicolaslee2775** [comment]
@louischan-oursky Rebased.

**Pull request merged**
