### PR TITLE
Fix duplicated completion call

### PR DESCRIPTION
**Pull request by kiootic**
ref #126

### CODE REVIEW

**Review by louischan-oursky — COMMENTED** [review]
If the problem is confirmed to be fixed by upgrading Xcode to 14.2, I guess we only need the 2nd commit in the PR.

**Comment by kiootic** [comment]
Removed the workaround commit.

**Comment by louischan-oursky** [comment]
@fungc-io Any updates? (Please share the updates on Slack)

**Comment by fungc-io** [comment]
No reply from the user

**Comment by fungc-io** [comment]
They don't want to update Xcode, 
but they said it works on "Release" build not "debug" build, so they will ignore the error..

**Comment by louischan-oursky** [comment]
https://github.com/authgear/authgear-sdk-ios/commit/e27651cc7e4cf23ff48b3dbd3cf9d6bb4587692a

**Pull request closed without merging**
