### PR TITLE
Revamp iOS demo app UI

### LINKED ISSUE #29: Use swiftUI to replace storyboard in demo app

### PR DESCRIPTION
**Pull request by axolotl0212**
fix #29

Use swift ui to replace storyboard

# Screenshot

Screenshot 2020-11-06 at 9 00 00 PM

### CODE REVIEW

**Comment by louischan-oursky** [comment]
Can we align the redirect_uri we use in all examples? Let's use this `com.authgear.example://host/path`

**Review by louischan-oursky — COMMENTED** [review]
1. Can we align the redirect_uri we use in all examples? Let's use this `com.authgear.example://host/path`
2. We should persist the last configured client_id and redirect_uri
3. Configure succeed without any feedback.
4. When keyboard is shown, the view is covered by the keyboard. Typically the view should be resized such that the view can be displayed by scrolling.
5. After login, there is no alert.
6. After login, clicking Fetch User Info has no effect.

**Comment by axolotl0212** [comment]
> 1. Can we align the redirect_uri we use in all examples? Let's use this `com.authgear.example://host/path`
> 2. We should persist the last configured client_id and redirect_uri
> 3. Configure succeed without any feedback.
> 4. When keyboard is shown, the view is covered by the keyboard. Typically the view should be resized such that the view can be displayed by scrolling.
> 5. After login, there is no alert.
> 6. After login, clicking Fetch User Info has no effect.
> 7. If possible, can we rewrite `iOS Example` so that the path does not have space? It is very inconvenient to have space in pathname, copy and paste in shell does not work without quoting :(

1. Sure
2. Will add this to demo app
3, 5, 6. That's weird, should have handled this, will investigate
4. Will research how to get keyboard avoiding view
7. You mean create a new app in new directory, the copy and paste source code?

@louischan-oursky

**Comment by axolotl0212** [comment]
@louischan-oursky addressed point 1~6, for point 7, could you suggest a name for the directory and bundle identifier so that all demo apps are aligned

**Comment by louischan-oursky** [comment]
The directory name can simply be `example`. The bundle identifier of the iOS example app could be `com.authgear.example.ios`

**Comment by axolotl0212** [comment]
@louischan-oursky changed bundle identifier, renamed project and move to `example` folder such that there is no space in path

**Pull request merged**
